#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/nginx

- name: Update apt cache
  ansible.builtin.apt:
    update-cache: yes
  tags: ["nginx"]

- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
  tags: ["nginx", "firewall"]

- name: Allow HTTP traffic
  ansible.builtin.ufw:
    rule: allow
    port: 80
    proto: tcp
  tags: ["nginx", "firewall"]

- name: Install Nginx package
  ansible.builtin.apt:
    name: nginx
    state: present
  tags: ["nginx"]

- name: Deploy custom nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload Nginx
  tags: ["nginx"]

- name: Enable and start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  tags: ["nginx"]