---
- name: Configuration Management for Linux Server (roadmap.sh project)
  hosts: gcp_hosts
  become: true
  roles:
    - { role: base, tags: ["base"] }
    - { role: nginx , tags: ["nginx"] }
    - { role: app, tags: ["app"] }
    - { role: ssh, tags: ["ssh"] }
