#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/base
#

# There are some redundant fail2ban procedures because I was having some problems with it
# So I'm just making sure that it properly starts and keeps working :)

# This is basically apt update apt upgrade
- name: Update apt cache
  apt:
    update-cache: yes

- name: Fix interrupted dpkg
  command: dpkg --configure -a
  become: true
  ignore_errors: true

- name: Upgrade all packages
  apt:
    upgrade: dist
    update_cache: yes
#

- name: Ensure fail2ban dependencies are installed
  apt:
    name:
      - iptables
      - rsyslog
    state: present

- name: Ensure rsyslog is running (required for fail2ban)
  service:
    name: rsyslog
    state: started
    enabled: yes
  ignore_errors: yes

# This is apt install <something>
- name: Install base utilities
  apt:
    name:
      - curl
      - vim
      - git
      - gzip
      - unzip
      - htop
    state: present

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
#


# This ensures the fail2ban service is running (such as starting it with service fail2ban start)
- name: Ensure fail2ban is running and enabled
  service:
    name: fail2ban
    state: started
    enabled: yes
  register: fail2ban_service_result
  ignore_errors: yes
#

# Yes try to start again because I was having problems with it
- name: Start fail2ban manually if service command failed
  command: fail2ban-client start
  when: fail2ban_service_result is failed
  ignore_errors: yes